import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "shashi",
    lastName: "Maurya",
    username: "shashi1",
    email: "shashimourya1@gmail.com",
    password: "shashi123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bio: "bio mein interest hota toh aaj mai doctor hota",
    profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654086752/shashi_maurya_xrox2a.jpg`,
    backgroundImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654089074/shashi_maurya_background_jcg8bi.jpg`,
    website: `https://shashikant-maurya.netlify.app/index.html`,
    follower: [
      {
        firstName: "Shailesh",
        lastName: "Kumar",
        username: "shailseen",
        profileImage: `https://media-exp1.licdn.com/dms/image/C4E03AQHVRCaHAAOL2g/profile-displayphoto-shrink_800_800/0/1632640634175?e=1660176000&v=beta&t=SBW6Uj2R8pEmluwxNABDf6WkkR6sst1yIt6MPDjIXM8`,
      },
      {
        firstName: `Kunal`,
        lastName: `Shah`,
        username: `kunalb11`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090092/kunal_shah_nvoz1m.jpg`,
      },
      {
        firstName: `Suumit`,
        lastName: `Shah`,
        username: `suumitshah`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090778/suumit_shah_mn2nhk.jpg`,
      },
      {
        firstName: `Bhavish`,
        lastName: ` Aggarwal`,
        username: `bhash`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654091110/bhavish_aggarwal_pc948b.jpg`,
      },
      {
        firstName: `Anupam`,
        lastName: `Mittal`,
        username: `AnupamMittal`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654092599/anupam_mittal_owirks.jpg`,
      },
    ],
    followings: [
      {
        firstName: "Shailesh",
        lastName: "Kumar",
        username: "shailseen",
        profileImage: `https://media-exp1.licdn.com/dms/image/C4E03AQHVRCaHAAOL2g/profile-displayphoto-shrink_800_800/0/1632640634175?e=1660176000&v=beta&t=SBW6Uj2R8pEmluwxNABDf6WkkR6sst1yIt6MPDjIXM8`,
      },
      {
        firstName: `Kunal`,
        lastName: `Shah`,
        username: `kunalb11`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090092/kunal_shah_nvoz1m.jpg`,
      },
      {
        firstName: `Suumit`,
        lastName: `Shah`,
        username: `suumitshah`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090778/suumit_shah_mn2nhk.jpg`,
      },
      {
        firstName: `Bhavish`,
        lastName: ` Aggarwal`,
        username: `bhash`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654091110/bhavish_aggarwal_pc948b.jpg`,
      },
      {
        firstName: `Anupam`,
        lastName: `Mittal`,
        username: `AnupamMittal`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654092599/anupam_mittal_owirks.jpg`,
      },
    ],
  },
  {
    _id: uuid(),
    firstName: "Shailesh",
    lastName: "Kumar",
    username: "shailseen",
    profileImage: `https://media-exp1.licdn.com/dms/image/C4E03AQHVRCaHAAOL2g/profile-displayphoto-shrink_800_800/0/1632640634175?e=1660176000&v=beta&t=SBW6Uj2R8pEmluwxNABDf6WkkR6sst1yIt6MPDjIXM8`,
    email: "shailesh@gmail.com",
    password: "shail1234",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bio: `Student  @neoG |  @Graphic era`,
    backgroundImage: `https://www.wallpapertip.com/wmimgs/83-838381_html-wallpaper-background-code-coding-tags.jpg`,
    follower: [
      {
        firstName: `Kunal`,
        lastName: `Shah`,
        username: `kunalb11`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090092/kunal_shah_nvoz1m.jpg`,
      },
      {
        firstName: `Suumit`,
        lastName: `Shah`,
        username: `suumitshah`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090778/suumit_shah_mn2nhk.jpg`,
      },
      {
        firstName: `Bhavish`,
        lastName: ` Aggarwal`,
        username: `bhash`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654091110/bhavish_aggarwal_pc948b.jpg`,
      },
    ],
    followings: [
      {
        firstName: `Suumit`,
        lastName: `Shah`,
        username: `suumitshah`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090778/suumit_shah_mn2nhk.jpg`,
      },
      {
        firstName: `Bhavish`,
        lastName: ` Aggarwal`,
        username: `bhash`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654091110/bhavish_aggarwal_pc948b.jpg`,
      },
      {
        firstName: `Anupam`,
        lastName: `Mittal`,
        username: `AnupamMittal`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654092599/anupam_mittal_owirks.jpg`,
      },
    ],
  },
  {
    _id: uuid(),
    firstName: "Kunal",
    lastName: "Shah",
    username: "kunalb11",
    email: "KunalShah@gmail.com",
    password: "shashi1234",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bio: "cred karo khush reho",
    profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090092/kunal_shah_nvoz1m.jpg`,
    website: null,
    backgroundImage: `https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60`,
    follower: [
      {
        firstName: `Suumit`,
        lastName: `Shah`,
        username: `suumitshah`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090778/suumit_shah_mn2nhk.jpg`,
      },
      {
        firstName: `Bhavish`,
        lastName: ` Aggarwal`,
        username: `bhash`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654091110/bhavish_aggarwal_pc948b.jpg`,
      },
    ],
    followings: [
      {
        firstName: `shashi`,
        lastName: `Maurya`,
        username: "shashi1",
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654086752/shashi_maurya_xrox2a.jpg`,
      },
      {
        firstName: "Shailesh",
        lastName: "Kumar",
        username: "shailseen",
        profileImage: `https://media-exp1.licdn.com/dms/image/C4E03AQHVRCaHAAOL2g/profile-displayphoto-shrink_800_800/0/1632640634175?e=1660176000&v=beta&t=SBW6Uj2R8pEmluwxNABDf6WkkR6sst1yIt6MPDjIXM8`,
      },
      {
        firstName: `Bhavish`,
        lastName: ` Aggarwal`,
        username: `bhash`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654091110/bhavish_aggarwal_pc948b.jpg`,
      },
    ],
  },

  {
    _id: uuid(),
    firstName: "Suumit",
    lastName: "Shah",
    username: "suumitshah",
    email: "suumitshah@gmail.com",
    password: "shashi1234",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bio: "Founder, Dukaan®",
    profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090778/suumit_shah_mn2nhk.jpg`,
    backgroundImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654098623/summit_shah_background_fffbxg.jpg`,
    website: `https://mydukaan.io/`,
    follower: [
      {
        firstName: "Shailesh",
        lastName: "Kumar",
        username: "shailseen",
        profileImage: `https://media-exp1.licdn.com/dms/image/C4E03AQHVRCaHAAOL2g/profile-displayphoto-shrink_800_800/0/1632640634175?e=1660176000&v=beta&t=SBW6Uj2R8pEmluwxNABDf6WkkR6sst1yIt6MPDjIXM8`,
      },
      {
        firstName: `Bhavish`,
        lastName: ` Aggarwal`,
        username: `bhash`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654091110/bhavish_aggarwal_pc948b.jpg`,
      },
      {
        firstName: `Anupam`,
        lastName: `Mittal`,
        username: `AnupamMittal`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654092599/anupam_mittal_owirks.jpg`,
      },
    ],
    followings: [
      {
        firstName: "Shailesh",
        lastName: "Kumar",
        username: "shailseen",
        profileImage: `https://media-exp1.licdn.com/dms/image/C4E03AQHVRCaHAAOL2g/profile-displayphoto-shrink_800_800/0/1632640634175?e=1660176000&v=beta&t=SBW6Uj2R8pEmluwxNABDf6WkkR6sst1yIt6MPDjIXM8`,
      },
      {
        firstName: `Kunal`,
        lastName: `Shah`,
        username: `kunalb11`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090092/kunal_shah_nvoz1m.jpg`,
      },
      {
        firstName: `Bhavish`,
        lastName: ` Aggarwal`,
        username: `bhash`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654091110/bhavish_aggarwal_pc948b.jpg`,
      },
      {
        firstName: `Anupam`,
        lastName: `Mittal`,
        username: `AnupamMittal`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654092599/anupam_mittal_owirks.jpg`,
      },
      {
        firstName: `shashi`,
        lastName: `Maurya`,
        username: "shashi1",
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654086752/shashi_maurya_xrox2a.jpg`,
      },
    ],
  },
  {
    _id: uuid(),
    firstName: "Bhavish",
    lastName: "Aggarwal",
    username: "bhash",
    email: "bhavishaggarwal@gmail.com",
    password: "shashi1234",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bio: `Building the future at Ola!
    `,
    profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654091110/bhavish_aggarwal_pc948b.jpg`,
    backgroundImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654100040/bhavish_aggarwal_background_vo5fmw.jpg`,
    website: `https://t.co/2fukVxoHsx`,
    follower: [
      {
        firstName: "Shailesh",
        lastName: "Kumar",
        username: "shailseen",
        profileImage: `https://media-exp1.licdn.com/dms/image/C4E03AQHVRCaHAAOL2g/profile-displayphoto-shrink_800_800/0/1632640634175?e=1660176000&v=beta&t=SBW6Uj2R8pEmluwxNABDf6WkkR6sst1yIt6MPDjIXM8`,
      },
      {
        firstName: `Kunal`,
        lastName: `Shah`,
        username: `kunalb11`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090092/kunal_shah_nvoz1m.jpg`,
      },
      {
        firstName: `Suumit`,
        lastName: `Shah`,
        username: `suumitshah`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090778/suumit_shah_mn2nhk.jpg`,
      },
    ],
    followings: [
      {
        firstName: `shashi`,
        lastName: `Maurya`,
        username: "shashi1",
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654086752/shashi_maurya_xrox2a.jpg`,
      },
      {
        firstName: "Shailesh",
        lastName: "Kumar",
        username: "shailseen",
        profileImage: `https://media-exp1.licdn.com/dms/image/C4E03AQHVRCaHAAOL2g/profile-displayphoto-shrink_800_800/0/1632640634175?e=1660176000&v=beta&t=SBW6Uj2R8pEmluwxNABDf6WkkR6sst1yIt6MPDjIXM8`,
      },
      {
        firstName: `Kunal`,
        lastName: `Shah`,
        username: `kunalb11`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090092/kunal_shah_nvoz1m.jpg`,
      },
      {
        firstName: `Suumit`,
        lastName: `Shah`,
        username: `suumitshah`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090778/suumit_shah_mn2nhk.jpg`,
      },
    ],
  },
  {
    _id: uuid(),
    firstName: "Anupam",
    lastName: "Mittal",
    username: "AnupamMittal",
    email: "AnupamMittal@gmail.com",
    password: "shashi1234",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bio: `Founder-People Group, Shaadi.com | Tech/Brand Investor | Shark`,
    profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654092599/anupam_mittal_owirks.jpg`,
    backgroundImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654101166/anupam_mittal_background_tlcaxw.jpg`,
    follower: [
      {
        firstName: "Shailesh",
        lastName: "Kumar",
        username: "shailseen",
        profileImage: `https://media-exp1.licdn.com/dms/image/C4E03AQHVRCaHAAOL2g/profile-displayphoto-shrink_800_800/0/1632640634175?e=1660176000&v=beta&t=SBW6Uj2R8pEmluwxNABDf6WkkR6sst1yIt6MPDjIXM8`,
      },
      {
        firstName: `Kunal`,
        lastName: `Shah`,
        username: `kunalb11`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090092/kunal_shah_nvoz1m.jpg`,
      },
      {
        firstName: `Suumit`,
        lastName: `Shah`,
        username: `suumitshah`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090778/suumit_shah_mn2nhk.jpg`,
      },
      {
        firstName: `Bhavish`,
        lastName: ` Aggarwal`,
        username: `bhash`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654091110/bhavish_aggarwal_pc948b.jpg`,
      },
    ],
    followings: [
      {
        firstName: `shashi`,
        lastName: `Maurya`,
        username: "shashi1",
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654086752/shashi_maurya_xrox2a.jpg`,
      },
      {
        firstName: "Shailesh",
        lastName: "Kumar",
        username: "shailseen",
        profileImage: `https://media-exp1.licdn.com/dms/image/C4E03AQHVRCaHAAOL2g/profile-displayphoto-shrink_800_800/0/1632640634175?e=1660176000&v=beta&t=SBW6Uj2R8pEmluwxNABDf6WkkR6sst1yIt6MPDjIXM8`,
      },
      {
        firstName: `Kunal`,
        lastName: `Shah`,
        username: `kunalb11`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090092/kunal_shah_nvoz1m.jpg`,
      },
      {
        firstName: `Suumit`,
        lastName: `Shah`,
        username: `suumitshah`,
        profileImage: `https://res.cloudinary.com/dwqdlzlek/image/upload/v1654090778/suumit_shah_mn2nhk.jpg`,
      },
    ],
  },
];
